site_name: systems-behavior-lab
site_description: Experiments investigating why systems behave the way they do
repo_url: https://github.com/jsleeair/systems-behavior-lab
repo_name: jsleeair/systems-behavior-lab

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - content.code.copy
    - toc.integrate

nav:
  - Home: index.md
  - Labs:
        - 00 Build & Binary:
                - 00 Translation Unit: 00-build-and-binary/00-translation-unit.md
                - 01 Weak vs Strong Symbol : 00-build-and-binary/01-weak-vs-strong-symbol.md
                - 02 Static vs Dynamic Link : 00-build-and-binary/02-static-vs-dynamic-link.md
                - 03 plt-got-analysis: 00-build-and-binary/03-plt-got-analysis.md
        - 01 Symbol Resolution:
                - 00 ELF Symbol Table: 01-symbol-resolution/00-elf-symbol-table.md
                - 01 Relocation Process: 01-symbol-resolution/01-relocation-process.md
                - 02 ABI and calling convention: 01-symbol-resolution/02-abi-and-calling-convention.md
        - 02 Memory Hierarchy:
                - 00 Cache Line Effect: 02-memory-hierarchy/00-cache-line-effect.md
                - 01 False Sharing: 02-memory-hierarchy/01-false-sharing.md
                - 02 TLB Effect: 02-memory-hierarchy/02-tlb-effect.md
                - 03 Prefetch and Locality: 02-memory-hierarchy/03-prefetch-and-locality.md
        - 03 OS Boundary:
                - 00 Syscall Cost: 03-os-boundary/00-syscall-cost.md
  - About: about.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
